BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "requests" (
	"ID"	INTEGER,
	"cid"	INTEGER,
	"ip"	TEXT,
	"request"	TEXT NOT NULL,
	"req_time"	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"comments"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE INDEX idx_requests_req_time
ON requests (req_time);
COMMIT;
