BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS requests (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    cid INTEGER,
    ip TEXT,
    request TEXT NOT NULL,
    req_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_requests_req_time
ON requests (req_time);
COMMIT;
